trigger: none

resources:
- repo: self

variables:
- name: tag
  value: $(Build.BuildId)
- name: ACR_REGISTRY
  value: cdlazrfinacr.azurecr.io 
- name: ACR_REPOSITORY
  value: app

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    variables:
    - name: ACR_REGISTRY
      value: cdlazrfinacr.azurecr.io 
   
    - name: ACR_REPOSITORY
      value: app
         

    steps:
    
    - task: Docker@2
      inputs:
        containerRegistry: 'CDLAZRFINACR_SC' 
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'CDLAZRFINACR_SC'
        repository: 'app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to Cluster
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy fineract frontend to AKS
    environment: 'CDL-AZR-FINAPP.application'  
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
           
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          # - task: KubectlInstaller@0
          #   inputs:
          #     kubectlVersion: 'latest'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo $ACR_REGISTRY
                echo $ACR_REPOSITORY
                echo $(Build.BuildId)
              
          #   displayName: 'Create fineract ui secret'
          #   workingDirectory: $(Pipeline.Workspace)/s/
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'CDL-AZR-FINAPP-CDL-AZR-FINAPP-application-1665737720754'
              namespace: 'application'
              manifests: '$(Pipeline.Workspace)/manifests/frontend.yaml'
              containers: '$(ACR_REGISTRY)/$(ACR_REPOSITORY):$(Build.BuildId)'
